/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: never;
        markDefs?: null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        post?: PostReference;
        _type: "featuredPost";
        _key: string;
      }
  >;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: AuthorReference;
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote" | "lead";
        listItem?: "checklist" | "steps";
        markDefs?: Array<
          | {
              href?: string;
              _type: "link";
              _key: string;
            }
          | {
              term?: string;
              _type: "glossaryTerm";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
    | {
        text?: string;
        attribution?: string;
        _type: "quote";
        _key: string;
      }
    | {
        language?: string;
        code?: string;
        filename?: string;
        _type: "code";
        _key: string;
      }
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | PostReference
  | Category
  | AuthorReference
  | SanityImageAssetReference
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Author
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: typegen.test-d.tsx
// Variable: postQuery
// Query: *[_type == "post" && slug.current == $slug][0]{title,author->{name,avatar},content}
export type PostQueryResult = {
  title: string | null;
  author: {
    name: string | null;
    avatar: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "lead" | "normal";
        listItem?: "checklist" | "steps";
        markDefs?: Array<
          | {
              term?: string;
              _type: "glossaryTerm";
              _key: string;
            }
          | {
              href?: string;
              _type: "link";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        language?: string;
        code?: string;
        filename?: string;
        _type: "code";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
    | {
        text?: string;
        attribution?: string;
        _type: "quote";
        _key: string;
      }
  > | null;
} | null;

// Source: typegen.test-d.tsx
// Variable: authorQuery
// Query: *[_type == "author" && _id == $id][0]{name,avatar,bio}
export type AuthorQueryResult = {
  name: string | null;
  avatar: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;

// Source: typegen.test-d.tsx
// Variable: categoryQuery
// Query: *[_type == "category" && _id == $id][0]{title,description[]{    ...,    _type == "featuredPost" => {      ...,      post->{title,author->{name,"avatar":avatar.asset->url},"slug":slug.current}    }  }}
export type CategoryQueryResult = {
  title: string | null;
  description: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: never;
        markDefs?: null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        post: {
          title: string | null;
          author: {
            name: string | null;
            avatar: string | null;
          } | null;
          slug: string | null;
        } | null;
        _type: "featuredPost";
        _key: string;
      }
  > | null;
} | null;

// Source: typegen.test-d.tsx
// Variable: mockQuery
// Query: *[_type in ["author", "category", "post"]]{      _type == "author" => {bio},      _type == "category" => {        description[]{          ...,          _type == "featuredPost" => {            ...,            post->{title,author->{name,"avatar":avatar.asset->url},"slug":slug.current}          }        }      },      _type == "post" => {content},    }
export type MockQueryResult = Array<
  | {
      bio: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: never;
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
    }
  | {
      content: Array<
        | {
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }>;
            style?: "blockquote" | "h2" | "h3" | "lead" | "normal";
            listItem?: "checklist" | "steps";
            markDefs?: Array<
              | {
                  term?: string;
                  _type: "glossaryTerm";
                  _key: string;
                }
              | {
                  href?: string;
                  _type: "link";
                  _key: string;
                }
            >;
            level?: number;
            _type: "block";
            _key: string;
          }
        | {
            language?: string;
            code?: string;
            filename?: string;
            _type: "code";
            _key: string;
          }
        | {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            caption?: string;
            _type: "image";
            _key: string;
          }
        | {
            text?: string;
            attribution?: string;
            _type: "quote";
            _key: string;
          }
      > | null;
    }
  | {
      description: Array<
        | {
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }>;
            style?: "normal";
            listItem?: never;
            markDefs?: null;
            level?: number;
            _type: "block";
            _key: string;
          }
        | {
            post: {
              title: string | null;
              author: {
                name: string | null;
                avatar: string | null;
              } | null;
              slug: string | null;
            } | null;
            _type: "featuredPost";
            _key: string;
          }
      > | null;
    }
>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "post" && slug.current == $slug][0]{title,author->{name,avatar},content}': PostQueryResult;
    '*[_type == "author" && _id == $id][0]{name,avatar,bio}': AuthorQueryResult;
    '*[_type == "category" && _id == $id][0]{title,description[]{\n    ...,\n    _type == "featuredPost" => {\n      ...,\n      post->{title,author->{name,"avatar":avatar.asset->url},"slug":slug.current}\n    }\n  }}': CategoryQueryResult;
    '*[_type in ["author", "category", "post"]]{\n      _type == "author" => {bio},\n      _type == "category" => {\n        description[]{\n          ...,\n          _type == "featuredPost" => {\n            ...,\n            post->{title,author->{name,"avatar":avatar.asset->url},"slug":slug.current}\n          }\n        }\n      },\n      _type == "post" => {content},\n    }': MockQueryResult;
  }
}
