name: Deploy to GitHub Pages

on:
  release:
    types: [published]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.ECOSCRIPT_APP_ID }}
          private-key: ${{ secrets.ECOSCRIPT_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version: lts/*
      - run: pnpm install
      - run: pnpm build
      - run: pnpm build:demo
      - uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          publish_dir: ./demo/dist
