name: Auto format

on:
  push:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read # for checkout

jobs:
  if-needed:
    uses: portabletext/.github/.github/workflows/format.yml@cd6af4198f189a0697c12c71758c50bc8c42d95e # main
    secrets: inherit
