name: Auto format

on:
  push:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read # for checkout

jobs:
  if-needed:
    uses: portabletext/.github/.github/workflows/format.yml@10bcd356478bb0808d82eab98b15c099c8730888 # main
    secrets: inherit
