name: Auto format

on:
  push:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read # for checkout

jobs:
  if-needed:
    uses: portabletext/.github/.github/workflows/format.yml@4d2d3a00346a628ab7dd0aa163a389e17b023157 # main
    secrets: inherit
