name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read # for checkout

jobs:
  release:
    uses: portabletext/.github/.github/workflows/changesets.yml@10bcd356478bb0808d82eab98b15c099c8730888 # main
    permissions:
      contents: read # for checkout
      id-token: write # to enable use of OIDC for npm provenance
    secrets: inherit
