name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read # for checkout

jobs:
  release:
    uses: portabletext/.github/.github/workflows/changesets.yml@a311e91e5c045a8986adf91bb0d3e35808e1704c # main
    permissions:
      contents: read # for checkout
      id-token: write # to enable use of OIDC for npm provenance
    secrets: inherit
