name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read # for checkout

jobs:
  release:
    uses: portabletext/.github/.github/workflows/changesets.yml@cd6af4198f189a0697c12c71758c50bc8c42d95e # main
    permissions:
      contents: read # for checkout
      id-token: write # to enable use of OIDC for npm provenance
    secrets: inherit
