name: Add changeset to Renovate updates

on:
  pull_request_target:
    types: [opened, synchronize]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read # for checkout

jobs:
  call:
    uses: portabletext/.github/.github/workflows/changesets-from-conventional-commits.yml@10bcd356478bb0808d82eab98b15c099c8730888 # main
    if: github.event.pull_request.user.login == 'renovate[bot]'
    secrets: inherit
