name: Add changeset to Renovate updates

on:
  pull_request_target:
    types: [opened, synchronize]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read # for checkout

jobs:
  call:
    uses: portabletext/.github/.github/workflows/changesets-from-conventional-commits.yml@cd6af4198f189a0697c12c71758c50bc8c42d95e # main
    if: github.event.pull_request.user.login == 'renovate[bot]'
    secrets: inherit
